stages:
  - test

ci-rollup:
  stage: test
  image: docker@sha256:851f91d241214e7c6db86513b270d58776379aacc5eb9c4a87e5b47115e3065c # 27.5.1-cli
  services:
    - name: docker@sha256:aa3df78ecf320f5fafdce71c659f1629e96e9de0968305fe1de670e0ca9176ce # 27.5.1-dind
      alias: docker
      command: ["--tls=false"]
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - apk add --no-cache bash coreutils python3
    - docker info
  script:
    - .ci_bridge/ci-bridge pipeline ci
    - .ci_bridge/test/contract_test.sh
